
# You'll need to create a PersistentVolume from which this
# PersistentVolumeClaim will claim its persistent volume.
# Ensure that your PersistentVolume's storageClassName is "influxdb".

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-persistent-volume-claim
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: influxdb

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-persistent-volume-claim  # This matches the persistent volume claim name above

---

apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
  name: monitoring-influxdb
  namespace: kube-system
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    k8s-app: influxdb